server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always  #显示health的全部细节
  endpoints:
    web:
      exposure:
        include: "*"  #默认只有health，开启全部

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-wait: 100
        min-idle: 0
        max-idle: 8
        max-active: 8
  application:
    name: gataway
  boot:
    admin:
      client:
        url: http://localhost:8081
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos地址
    gateway:
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能， 动态路由
      routes:
        - id: system-service
          uri: lb://systemservice
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1


      #      跨域配置
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allow-credentials: true #允许携带cookie
            allowedOriginPatterns: "*"
            allowed-origins: "*" #允许跨域的请求，设置*为全部
            allowed-headers: "*" #允许跨域请求里的head字段，设置*为全部
            allowed-methods: "*" #允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowCredentials: true # 是否允许携带cookie
            max-age: 360000

# 日志相关
logging:
  pattern:
    console: "%d{MM.dd HH:ss} %clr(%p) [%clr(%-10.10t){blue}] %clr(%-25.25c){cyan} : %clr(%m) %clr(%n)"
